### ISSUE TITLE
New columns for report table

### ISSUE THREAD

**Issue by dereklieu** [developmentseed/nethope-sitrep-api#1]
Not urgent, but keeping a running thread of new columns we will need to add to the report table.

1. tags (many-to-many key to a separate tag table?)

**Comment by drewbo** [comment]
@dereklieu is the separate tag table so we can fetch a unique list of tags? Or could this just be an array or jsonb field in the report model?

**Comment by dereklieu** [comment]
Yeah, fetching a unique list and facilitating the ability of someone to add to or remove from that list

**Comment by dereklieu** [comment]
Also, having a separate table probably (though not necessarily) makes it easier to query records with that tag?
